/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressResolver } from "./AddressResolver";
export type { ContentHashResolver } from "./ContentHashResolver";
export type { IAddressResolver } from "./IAddressResolver";
export type { IContentHashResolver } from "./IContentHashResolver";
export type { INameResolver } from "./INameResolver";
export type { ITextResolver } from "./ITextResolver";
export type { IVersionableResolver } from "./IVersionableResolver";
export type { NameResolver } from "./NameResolver";
export type { TextResolver } from "./TextResolver";
