/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMulticallable,
  IMulticallableInterface,
} from "../../interfaces/IMulticallable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicallWithNodeCheck",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMulticallable__factory {
  static readonly abi = _abi;
  static createInterface(): IMulticallableInterface {
    return new utils.Interface(_abi) as IMulticallableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMulticallable {
    return new Contract(address, _abi, signerOrProvider) as IMulticallable;
  }
}
