/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IContentHashResolver,
  IContentHashResolverInterface,
} from "../../resolvers/IContentHashResolver";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "hash",
        type: "bytes",
      },
    ],
    name: "ContenthashChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "contenthash",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IContentHashResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IContentHashResolverInterface {
    return new utils.Interface(_abi) as IContentHashResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IContentHashResolver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IContentHashResolver;
  }
}
