/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  INameResolver,
  INameResolverInterface,
} from "../../resolvers/INameResolver";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "NameChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
    ],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class INameResolver__factory {
  static readonly abi = _abi;
  static createInterface(): INameResolverInterface {
    return new utils.Interface(_abi) as INameResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INameResolver {
    return new Contract(address, _abi, signerOrProvider) as INameResolver;
  }
}
