/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FNS } from "./FNS";
export type { IMulticallable } from "./IMulticallable";
export type { IPriceOracle } from "./IPriceOracle";
export type { IRegistrar } from "./IRegistrar";
export type { IRegistrarController } from "./IRegistrarController";
export type { IResolver } from "./IResolver";
export type { IReverseRegistrar } from "./IReverseRegistrar";
